name: ransac
channels:
  - open3d-admin
dependencies:
  - python=3.7
  - pip
  - numpy
  - opencv
  - matplotlib
  - scikit-learn
  - pip:
    - opencv-contrib-python
    - addict
    - pandas
    - plyfile
    - sklearn
    - tqdm
    - pyyaml
  - open3d
